#!/bin/bash



ssid="Your SSID Here"

#possible values here are OPEN, WPA, WPAE (WPA Enterprise), WPA2, WPAE2, WEP or 8021XWEP
securitytype="WPA2"

password="myverysecurepassword"


device=$(networksetup -listallhardwareports | grep -E '(Wi-Fi|AirPort)' -A 1 | grep -o en.)

if [ $device != "" ]
	then
	networksetup -addpreferredwirelessnetworkatindex $device $ssid 0 $securitytype $password
fi

exit 0