USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make
TITLE=scriptRunnerToOutset
REVERSE_DOMAIN=com.grahamgilbert
PAYLOAD= \
	pack-script-postinstall \
	pack-usr-local-outset-on-demand-01-scriptRunnerToOutset_user_plist.py

