#!/usr/bin/python

import sys
import os
import time
from urllib2 import urlopen, URLError

from munkilib import munkicommon

def network_on():
    try:
        response=urlopen(munkicommon.pref('SoftwareRepoURL'),timeout=1)
        return True
    except URLError as err: pass
    return False

bootstrap_file = '/Users/Shared/.com.googlecode.munki.checkandinstallatstartup'

# Does the bootstrap file exist?
if os.path.exists(bootstrap_file):
    # check that the server is reachable
    serverUp = False
    for unused_i in range(5):
        if network_on():
            serverUp = True
            break
        time.sleep(2)
    if not serverUp:
        # if the server is down, remove the file
        os.unlink(bootstrap_file)