include /usr/local/share/luggage/luggage.make

TITLE=re-enable-java
PACKAGE_NAME=re-enable-java
PACKAGE_TARGET_OS=10.5
PLIST_FLAVOR=pkg-info
REVERSE_DOMAIN=com.grahamgilbert
PAYLOAD=\
	pack-script-postflight